##Import necessary libraries

In [44]:
import requests as re
from bs4 import BeautifulSoup
import numpy as np
print("Finish importing libraries successfully!")

Finish importing libraries successfully!


##About 1 product
I try to get request from this [link of product](https://laptopaz.vn/new-100-asus-rog-zephyrus-g15-ga503rm-ryzen-7-6800hs-16gb-512gb-rtx-3060-6gb-15.6-qhd-165hz.html)


In [45]:
link = 'https://laptopaz.vn/new-100-asus-rog-zephyrus-g15-ga503rm-ryzen-7-6800hs-16gb-512gb-rtx-3060-6gb-15.6-qhd-165hz.html'
resp = re.get(link)

Use BeautifulSoup to get the content of html of this link

In [46]:
soup = BeautifulSoup(resp.content)
soup

<!DOCTYPE html>
<html>
<head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-59VT8GL');</script>
<!-- End Google Tag Manager -->
<meta content="HkPvwF-GEqRGKpk4qYS1N2v9bpgtgsNI3RDFvFblyu0" name="google-site-verification"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<title>[New 100%] Asus ROG Zephyrus G15 GA503RM (Ryzen 7-6800HS, 16GB, 512GB, RTX 3060 6GB, 15.6'' QHD+ 240Hz)</title>
<meta content="index,follow" name="robots"/>
<meta content="" name="keywords"/>
<meta content="" name="description"/>
<meta content="DOCUMENT" name="RESOURCE-TYPE"/>
<meta content="vi" http-equiv="content-language"/>
<!--<meta name="viewport" content="width=device-widt

* soup contains html of website named Laptopaz, this product is **"[New 100%] Asus ROG Zephyrus G15 GA503RM (Ryzen 7-6800HS, 16GB, 512GB, RTX 3060 6GB, 15.6'' QHD+ 240Hz)"**
* Basic information of a product: Name, Price, Brand, Expiry Date, number of stocks, sells, number of feedback, feedback score.

If we want to get the price

In [47]:
price = soup.find(class_ = 'show-him bk-product-price').text.strip()
price

'28.390.000'

In [48]:
information = soup.find(class_ = 'bk-product-name').text.strip()
information

"[New 100%] Asus ROG Zephyrus G15 GA503RM (Ryzen 7-6800HS, 16GB, 512GB, RTX 3060 6GB, 15.6'' QHD+ 240Hz)"

In [49]:
# information = information.split()
# information

# get status, name, parameters
l = len(information)
for i in range(l):
  # if information[i] == '[':
  #   status1 = i
  if information[i] == ']':
    status2 = i
  if information[i] == '(':
    para1 = i
  # if information[i] == ')':
  #   para2 = i

status = information[1 : status2].strip()
name = information[status2+1 : para1].strip()
parameters = information[para1+1 : -1]
print(status)
print(name)
print(parameters)

New 100%
Asus ROG Zephyrus G15 GA503RM
Ryzen 7-6800HS, 16GB, 512GB, RTX 3060 6GB, 15.6'' QHD+ 240Hz


In [50]:
parameters = parameters.split(',')
parameters
cpu = parameters[0].strip()
ram = parameters[1].strip()
hard = parameters[2].strip()
gpu = parameters[3].strip()
screen = parameters[-1].strip()
hard

'512GB'

In [51]:
print(cpu, ram, hard, gpu,screen)

Ryzen 7-6800HS 16GB 512GB RTX 3060 6GB 15.6'' QHD+ 240Hz


In [52]:
warranty = soup.find(class_ = 'unprice').find('p')
warranty

<p style="margin-bottom: 5px;"><strong>Bảo hành: </strong>12 tháng tại LaptopAZ </p>

In [53]:
stock = soup.find(class_ = 'detail-quantity')
stock

<div class="detail-quantity"><b>Tình trạng:</b> <span class="con">Còn hàng</span></div>

## About 1 page with many products

In [54]:
link_list = []
for i in range(8):
    resp = re.get('https://laptopaz.vn/laptop-gaming.html?page='+str(i))
    # print(resp.status_code)
    # if resp.status_code == 200:
    soup = BeautifulSoup(resp.content)
    links = soup.find_all(class_ = 'p-name')
    print(links)
    for link in links[::2]:
      link_list.append('https://laptopaz.vn'+link['href'])
    # print(link_list)

[<a class="p-name" href="/new-100-lenovo-legion-5-core-i7-11800h-16gb-512gb-rtx-3060-15.6quot-2k-165hz-100-srgb.html">[New 100%] Lenovo Legion 5 (Core i7-11800H, 16GB, 512GB, RTX 3060, 15.6" 2K 165Hz 100% sRGB)</a>, <a class="p-name" href="/new-100-lenovo-legion-5-core-i7-11800h-16gb-512gb-rtx-3060-15.6quot-2k-165hz-100-srgb.html">[New 100%] Lenovo Legion 5 (Core i7-11800H, 16GB, 512GB, RTX 3060, 15.6" 2K 165Hz 100% sRGB)</a>, <a class="p-name" href="/new-100-asus-rog-zephyrus-g15-ga503rm-ryzen-7-6800hs-16gb-512gb-rtx-3060-6gb-15.6-qhd-165hz.html">[New 100%] Asus ROG Zephyrus G15 GA503RM (Ryzen 7-6800HS, 16GB, 512GB, RTX 3060 6GB, 15.6'' QHD+ 240Hz)</a>, <a class="p-name" href="/new-100-asus-rog-zephyrus-g15-ga503rm-ryzen-7-6800hs-16gb-512gb-rtx-3060-6gb-15.6-qhd-165hz.html">[New 100%] Asus ROG Zephyrus G15 GA503RM (Ryzen 7-6800HS, 16GB, 512GB, RTX 3060 6GB, 15.6'' QHD+ 240Hz)</a>, <a class="p-name" href="/new-100-lenovo-loq-2023-82xv002lus-core-i5-13420h-8gb-1tb-rtx-3050-6gb-15.6quot-

In [55]:
link_list

['https://laptopaz.vn/new-100-lenovo-legion-5-core-i7-11800h-16gb-512gb-rtx-3060-15.6quot-2k-165hz-100-srgb.html',
 'https://laptopaz.vn/new-100-asus-rog-zephyrus-g15-ga503rm-ryzen-7-6800hs-16gb-512gb-rtx-3060-6gb-15.6-qhd-165hz.html',
 'https://laptopaz.vn/new-100-lenovo-loq-2023-82xv002lus-core-i5-13420h-8gb-1tb-rtx-3050-6gb-15.6quot-fhd-144hz.html',
 'https://laptopaz.vn/new-100-lenovo-legion-slim-5-2023-y7000p-core-i7-13700h-16gb-1tb-rtx-4060-8gb-16-2k-165hz.html',
 'https://laptopaz.vn/moi-100-acer-nitro-16-2023-core-i5-13500h-16gb-512gb-rtx-4050-6gb-16quot-fhd-ips-165hz.html',
 'https://laptopaz.vn/lenovo-legion-pro-5-y9000p-2023-core-i9-13900hx-16gb-1tb-rtx-4060-8gb-16quot-wqxga-240hz.html',
 'https://laptopaz.vn/dell-gaming-g15-5525-ryzen-5-6600h-8gb-512gb-rtx-3050-4gb-15.6-fhd-120hz.html',
 'https://laptopaz.vn/acer-nitro-5-2022-an517-55-core-i5-12500h-8gb-512gb-rtx-3050-17.3quot-fhd-ips-144hz.html',
 'https://laptopaz.vn/moi-100-acer-gaming-predator-helios-300-2022-ph315-55-7

In [56]:
# link_list[::2]

In [57]:
list_price = []
list_information = []
list_warranty = []
list_stock = []

In [58]:
list_price = []
list_information = []
list_warranty = []
list_stock = []

# for link in link_list[:1]:
link = link_list[0]
resp = re.get(link)
soup = BeautifulSoup(resp.content,'html.parser')
# if (not soup.find(class_='price')) or (len(soup.find_all(class_='info-attr')) != 6): continue
list_price.append(soup.find(class_ = 'bk-product-price').text.strip())
list_information.append(soup.find(class_ = 'bk-product-name').text.strip())
list_warranty.append(soup.find(class_ = 'col column-2').find('p').text[10:].strip())
list_stock.append(soup.find(class_ = 'detail-quantity').find('span').text.strip())

print(list_price)
print(list_information)
print(list_warranty)
print(list_stock)

['24.990.000']
['[New 100%] Lenovo Legion 5 (Core i7-11800H, 16GB, 512GB, RTX 3060, 15.6" 2K 165Hz 100% sRGB)']
['12 tháng LaptopAZ']
['Còn hàng']


In [59]:
len(link_list)

320

In [61]:
list_price = []
list_information = []
list_warranty = []
list_stock = []

for link in link_list:
  try:
    resp = re.get(link)
    soup = BeautifulSoup(resp.content,'html.parser')
    if (not soup.find(class_='bk-product-price')): list_price.append("None")
    else: list_price.append(soup.find(class_ = 'bk-product-price').text.strip())
    if (not soup.find(class_='bk-product-name')): list_information.append("None")
    else: list_information.append(soup.find(class_ = 'bk-product-name').text.strip())
    if (not soup.find(class_='col column-2')): list_warranty.append ("None")
    else: list_warranty.append(soup.find(class_ = 'col column-2').find('p').text[10:].strip())
    if (not soup.find(class_='detail-quantity')): list_stock.append("None")
    else: list_stock.append(soup.find(class_ = 'detail-quantity').find('span').text.strip())
  except:
    continue

In [62]:
list_price

['24.990.000',
 '28.390.000',
 '19.890.000',
 '32.890.000',
 '25.690.000',
 '39.890.000',
 '17.990.000',
 '17.990.000',
 '27.990.000',
 '16.990.000',
 '22.990.000',
 '21.790.000',
 '23.890.000',
 '27.890.000',
 '26.490.000',
 '23.890.000',
 '18.890.000',
 '35.890.000',
 '24.690.000',
 '35.890.000',
 '20.890.000',
 '29.890.000',
 '26.890.000',
 '25.890.000',
 '28.890.000',
 '34.890.000',
 '24.890.000',
 '25.990.000',
 '28.890.000',
 '21.890.000',
 '19.890.000',
 '22.890.000',
 '26.890.000',
 '20.890.000',
 'None',
 '13.890.000',
 '35.890.000',
 '25.990.000',
 '22.790.000',
 '29.590.000',
 '24.990.000',
 '28.390.000',
 '19.890.000',
 '32.890.000',
 '25.690.000',
 '39.890.000',
 '17.990.000',
 '17.990.000',
 '27.990.000',
 '16.990.000',
 '22.990.000',
 '21.790.000',
 '23.890.000',
 '27.890.000',
 '26.490.000',
 '23.890.000',
 '18.890.000',
 '35.890.000',
 '24.690.000',
 '35.890.000',
 '20.890.000',
 '29.890.000',
 '26.890.000',
 '25.890.000',
 '28.890.000',
 '34.890.000',
 '24.890.000',
 

In [63]:
len(list_price), len(list_information), len(list_warranty), len(list_stock)

(320, 320, 320, 320)

Explain: Why this page has 40 products, but list of price just has 39 products?
Reason: 1 product is updating the price, it is not public!

In [64]:
list_information

['[New 100%] Lenovo Legion 5 (Core i7-11800H, 16GB, 512GB, RTX 3060, 15.6" 2K 165Hz 100% sRGB)',
 "[New 100%] Asus ROG Zephyrus G15 GA503RM (Ryzen 7-6800HS, 16GB, 512GB, RTX 3060 6GB, 15.6'' QHD+ 240Hz)",
 '[New 100%] Lenovo LOQ 2023 82XV002LUS (Core i5-13420H, 8GB, 1TB, RTX 3050 6GB, 15.6" FHD 144Hz)',
 "[New 100%] Lenovo Legion Slim 5 2023 (Y7000P) (Core i7-13700H, 16GB, 1TB, RTX 4060 8GB, 16'' 2K+ 165Hz)",
 '[New 100%] Acer Nitro 16 2023 (Core i5-13500H, 16GB, 512GB, RTX 4050 6GB, 16" FHD+ IPS 165Hz)',
 '[New 100%] Lenovo Legion Pro 5 Y9000P 2023 (Core i9-13900HX, 16GB, 1TB, RTX 4060 8GB, 16" WQXGA 240Hz)',
 "[New 100%] Dell Gaming G15 5525 (Ryzen 5-6600H, 8GB, 512GB, RTX 3050 4GB, 15.6'' FHD 120Hz)",
 '[New Outlet] Acer Nitro 5 2022 AN517-55 (Core i5-12500H, 8GB, 512GB, RTX 3050, 17.3" FHD IPS 144Hz)',
 "[New 100%] Acer Gaming Predator Helios 300 2022 PH315-55-70ZV (Core i7-12700H, 16GB, 512GB, RTX 3060 6GB, 15.6'' FHD 165Hz)",
 '[New Outlet]  Acer Nitro 5 2022 AN517-55 (Core i5 - 

In [66]:
list_stock

['Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Liên hệ',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Liên hệ',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Liên hệ',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Còn hàng',
 'Liên hệ',
 'Còn hàng',
 'C

In [67]:
list_warranty

['12 tháng LaptopAZ',
 '12 tháng tại LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '24 tháng Asus Việt Nam',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng tại LaptopAZ',
 '12 tháng Laptop AZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng tại LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng Laptop AZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '24 tháng Gigabyte Việt Nam',
 '24 tháng Gigabyte Việt Nam',
 '12 tháng LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng tại LaptopAZ',
 '12 tháng LaptopAZ',
 '12 tháng La

In [74]:
# treat the information
list_status = []
list_name = []
list_parameters = []

# get status, name, parameters
for information in list_information:
  if information[0] =='[':
    l = len(information)
    # for i in range(l):
    #   # if information[i] == '[':
    #   #   status1 = i
    #   if information[i] == ']':
    #     status2 = i
    #   if information[i] == '(':
    #     para1 = i
    #   # if information[i] == ')':
    #   #   para2 = i
    status2 = information.find(']')
    para1 = information.find('(')

    status = information[1 : status2].strip()
    name = information[status2+1 : para1].strip()
    parameters = information[para1+1 : -1]

    parameters = parameters.split(',')
    cpu = parameters[0].strip()
    ram = parameters[1].strip()
    hard = parameters[2].strip()
    gpu = parameters[3].strip()
    screen = parameters[-1].strip()

    list_status.append(status)
    list_name.append(name)
    list_parameters.append([cpu, ram, hard, gpu, screen])
  else:
    list_status.append('None')
    list_name.append('None')
    list_parameters.append(['None']*5)

In [75]:
len(list_status)

320

In [76]:
list_status

['New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New 100%',
 'Like New',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New 100%',
 'New 100%',
 'New 100%',
 'New Outlet',
 'New 100%',
 'New 100%',
 'Lik

In [77]:
list_parameters

[['Core i7-11800H', '16GB', '512GB', 'RTX 3060', '15.6" 2K 165Hz 100% sRGB'],
 ['Ryzen 7-6800HS', '16GB', '512GB', 'RTX 3060 6GB', "15.6'' QHD+ 240Hz"],
 ['Core i5-13420H', '8GB', '1TB', 'RTX 3050 6GB', '15.6" FHD 144Hz'],
 ['Y7000P) (Core i7-13700H', '16GB', '1TB', 'RTX 4060 8GB', "16'' 2K+ 165Hz"],
 ['Core i5-13500H', '16GB', '512GB', 'RTX 4050 6GB', '16" FHD+ IPS 165Hz'],
 ['Core i9-13900HX', '16GB', '1TB', 'RTX 4060 8GB', '16" WQXGA 240Hz'],
 ['Ryzen 5-6600H', '8GB', '512GB', 'RTX 3050 4GB', "15.6'' FHD 120Hz"],
 ['Core i5-12500H', '8GB', '512GB', 'RTX 3050', '17.3" FHD IPS 144Hz'],
 ['Core i7-12700H', '16GB', '512GB', 'RTX 3060 6GB', "15.6'' FHD 165Hz"],
 ['Core i5 - 12500H', '8GB', '256GB', 'RTX 3050', '17.3" FHD IPS 144Hz'],
 ['Ryzen 7-5800HS', '16GB', '512GB', 'RTX 3060', '14" FHD IPS 144Hz'],
 ['Ryzen 7-6800HS', '8GB', '512GB', 'RTX 3050', "15.6'' FHD 144Hz"],
 ['Core i7 - 12700H', '8GB', '512GB', 'RTX 3050Ti', '15.6" FHD IPS 144Hz'],
 ['Ryzen 7 - 5800H', '16GB', '512GB', 'RTX

### Create dataframe


In [78]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Column:


* price
* warranty
* stock
* status
* name
* parameters: cpu, ram, hard, gpu, screen


In [79]:
df1 = pd.DataFrame(list_price, columns = ["Price"])
df2 = pd.DataFrame(list_name, columns = ["Name"])
df3 = pd.DataFrame(list_parameters, columns = ['CPU', 'RAM', 'Hard Disk', 'GPU', 'Screen'])
df4 = pd.DataFrame(list_warranty, columns = ["Warranty"])
df5 = pd.DataFrame(list_stock, columns = ["Stock"])
df6 = pd.DataFrame(list_status, columns = ["Status"])
df = pd.concat([df1,df2,df3,df4,df5,df6],axis = 1)

In [80]:
df

Price                           Name                      CPU   RAM  \
0    24.990.000                Lenovo Legion 5           Core i7-11800H  16GB   
1    28.390.000  Asus ROG Zephyrus G15 GA503RM           Ryzen 7-6800HS  16GB   
2    19.890.000     Lenovo LOQ 2023 82XV002LUS           Core i5-13420H   8GB   
3    32.890.000      Lenovo Legion Slim 5 2023  Y7000P) (Core i7-13700H  16GB   
4    25.690.000             Acer Nitro 16 2023           Core i5-13500H  16GB   
..          ...                            ...                      ...   ...   
315        None           Lenovo Legion 5 2021            Ryzen 7-5800H   8GB   
316        None        Lenovo Ideapad Gaming 3            Ryzen 5-5600H   8GB   
317        None        Asus TUF Gaming FX706HC           Core i5-11260H   8GB   
318        None         Dell Gaming G5 15 5511           Core i7-11800H  16GB   
319        None        Lenovo Ideapad Gaming 3            Ryzen 5-5600H   8GB   

    Hard Disk           GPU                    Screen               Warranty  \
0       512GB      RTX 3060  15.6" 2K 165Hz 100% sRGB      12 tháng LaptopAZ   
1       512GB  RTX 3060 6GB         15.6'' QHD+ 240Hz  12 tháng tại LaptopAZ   
2         1TB  RTX 3050 6GB           15.6" FHD 144Hz      12 tháng LaptopAZ   
3         1TB  RTX 4060 8GB            16'' 2K+ 165Hz      12 tháng LaptopAZ   
4       512GB  RTX 4050 6GB        16" FHD+ IPS 165Hz      12 tháng LaptopAZ   
..        ...           ...                       ...                    ...   
315     512GB    RTX 3050Ti          15.6'' FHD 165Hz      12 tháng LaptopAZ   
316     512GB    RTX 3050Ti       15.6" FHD IPS 120Hz     12 tháng Laptop AZ   
317     512GB      RTX 3050       17.3″ FHD IPS 144Hz             khuyến mại   
318     512GB      RTX 3060          15.6'' FHD 165Hz     12 tháng Laptop AZ   
319     512GB      RTX 3060       15.6" FHD IPS 120Hz     12 tháng Laptop AZ   

        Stock    Status  
0    Còn hàng  New 100%  
1    Còn hàng  New 100%  
2    Còn hàng  New 100%  
3    Còn hàng  New 100%  
4    Còn hàng  New 100%  
..        ...       ...  
315   Liên hệ  Mới 100%  
316   Liên hệ  Mới 100%  
317   Liên hệ  Mới 100%  
318   Liên hệ  New 100%  
319   Liên hệ  Mới 100%  

[320 rows x 10 columns]

Finish crawl data!!!

In [81]:
raw_df = df.copy()
raw_df.to_csv('raw_data.csv', index=False)

In [82]:
raw_df

Price                           Name                      CPU   RAM  \
0    24.990.000                Lenovo Legion 5           Core i7-11800H  16GB   
1    28.390.000  Asus ROG Zephyrus G15 GA503RM           Ryzen 7-6800HS  16GB   
2    19.890.000     Lenovo LOQ 2023 82XV002LUS           Core i5-13420H   8GB   
3    32.890.000      Lenovo Legion Slim 5 2023  Y7000P) (Core i7-13700H  16GB   
4    25.690.000             Acer Nitro 16 2023           Core i5-13500H  16GB   
..          ...                            ...                      ...   ...   
315        None           Lenovo Legion 5 2021            Ryzen 7-5800H   8GB   
316        None        Lenovo Ideapad Gaming 3            Ryzen 5-5600H   8GB   
317        None        Asus TUF Gaming FX706HC           Core i5-11260H   8GB   
318        None         Dell Gaming G5 15 5511           Core i7-11800H  16GB   
319        None        Lenovo Ideapad Gaming 3            Ryzen 5-5600H   8GB   

    Hard Disk           GPU                    Screen               Warranty  \
0       512GB      RTX 3060  15.6" 2K 165Hz 100% sRGB      12 tháng LaptopAZ   
1       512GB  RTX 3060 6GB         15.6'' QHD+ 240Hz  12 tháng tại LaptopAZ   
2         1TB  RTX 3050 6GB           15.6" FHD 144Hz      12 tháng LaptopAZ   
3         1TB  RTX 4060 8GB            16'' 2K+ 165Hz      12 tháng LaptopAZ   
4       512GB  RTX 4050 6GB        16" FHD+ IPS 165Hz      12 tháng LaptopAZ   
..        ...           ...                       ...                    ...   
315     512GB    RTX 3050Ti          15.6'' FHD 165Hz      12 tháng LaptopAZ   
316     512GB    RTX 3050Ti       15.6" FHD IPS 120Hz     12 tháng Laptop AZ   
317     512GB      RTX 3050       17.3″ FHD IPS 144Hz             khuyến mại   
318     512GB      RTX 3060          15.6'' FHD 165Hz     12 tháng Laptop AZ   
319     512GB      RTX 3060       15.6" FHD IPS 120Hz     12 tháng Laptop AZ   

        Stock    Status  
0    Còn hàng  New 100%  
1    Còn hàng  New 100%  
2    Còn hàng  New 100%  
3    Còn hàng  New 100%  
4    Còn hàng  New 100%  
..        ...       ...  
315   Liên hệ  Mới 100%  
316   Liên hệ  Mới 100%  
317   Liên hệ  Mới 100%  
318   Liên hệ  New 100%  
319   Liên hệ  Mới 100%  

[320 rows x 10 columns]

## Clean data

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Price      320 non-null    object
 1   Name       320 non-null    object
 2   CPU        320 non-null    object
 3   RAM        320 non-null    object
 4   Hard Disk  320 non-null    object
 5   GPU        320 non-null    object
 6   Screen     320 non-null    object
 7   Warranty   320 non-null    object
 8   Stock      320 non-null    object
 9   Status     320 non-null    object
dtypes: object(10)
memory usage: 25.1+ KB


#### Problem 1: Column name 'Price'
* Not uniform.
* Type: Object

In [84]:
# #  Check first value
# price = df['Price'][0]
# price = int(price.replace('.',''))/1000000
# price

In [85]:
df['Price'] = raw_df['Price']
df['Price']

0      24.990.000
1      28.390.000
2      19.890.000
3      32.890.000
4      25.690.000
          ...    
315          None
316          None
317          None
318          None
319          None
Name: Price, Length: 320, dtype: object

In [86]:
list_price1 = np.array([])
for i in range(len(df['Price'])):
  price_ = str(df['Price'][i])
  if price_ != 'None':
    if price_[-1].isdigit() == False:
      price_ = price_[:-1]
    price_ = int(price_.replace('.',''))/1000000
    list_price1 = np.append(list_price1, price_)
  else:
    list_price1 = np.append(list_price1, np.nan)
# list_price1
df['Price'] = list_price1
df = df.rename(columns={'Price': 'Price (Million VND)'})
df

Price (Million VND)                           Name  \
0                  24.99                Lenovo Legion 5   
1                  28.39  Asus ROG Zephyrus G15 GA503RM   
2                  19.89     Lenovo LOQ 2023 82XV002LUS   
3                  32.89      Lenovo Legion Slim 5 2023   
4                  25.69             Acer Nitro 16 2023   
..                   ...                            ...   
315                  NaN           Lenovo Legion 5 2021   
316                  NaN        Lenovo Ideapad Gaming 3   
317                  NaN        Asus TUF Gaming FX706HC   
318                  NaN         Dell Gaming G5 15 5511   
319                  NaN        Lenovo Ideapad Gaming 3   

                         CPU   RAM Hard Disk           GPU  \
0             Core i7-11800H  16GB     512GB      RTX 3060   
1             Ryzen 7-6800HS  16GB     512GB  RTX 3060 6GB   
2             Core i5-13420H   8GB       1TB  RTX 3050 6GB   
3    Y7000P) (Core i7-13700H  16GB       1TB  RTX 4060 8GB   
4             Core i5-13500H  16GB     512GB  RTX 4050 6GB   
..                       ...   ...       ...           ...   
315            Ryzen 7-5800H   8GB     512GB    RTX 3050Ti   
316            Ryzen 5-5600H   8GB     512GB    RTX 3050Ti   
317           Core i5-11260H   8GB     512GB      RTX 3050   
318           Core i7-11800H  16GB     512GB      RTX 3060   
319            Ryzen 5-5600H   8GB     512GB      RTX 3060   

                       Screen               Warranty     Stock    Status  
0    15.6" 2K 165Hz 100% sRGB      12 tháng LaptopAZ  Còn hàng  New 100%  
1           15.6'' QHD+ 240Hz  12 tháng tại LaptopAZ  Còn hàng  New 100%  
2             15.6" FHD 144Hz      12 tháng LaptopAZ  Còn hàng  New 100%  
3              16'' 2K+ 165Hz      12 tháng LaptopAZ  Còn hàng  New 100%  
4          16" FHD+ IPS 165Hz      12 tháng LaptopAZ  Còn hàng  New 100%  
..                        ...                    ...       ...       ...  
315          15.6'' FHD 165Hz      12 tháng LaptopAZ   Liên hệ  Mới 100%  
316       15.6" FHD IPS 120Hz     12 tháng Laptop AZ   Liên hệ  Mới 100%  
317       17.3″ FHD IPS 144Hz             khuyến mại   Liên hệ  Mới 100%  
318          15.6'' FHD 165Hz     12 tháng Laptop AZ   Liên hệ  New 100%  
319       15.6" FHD IPS 120Hz     12 tháng Laptop AZ   Liên hệ  Mới 100%  

[320 rows x 10 columns]

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Price (Million VND)  150 non-null    float64
 1   Name                 320 non-null    object 
 2   CPU                  320 non-null    object 
 3   RAM                  320 non-null    object 
 4   Hard Disk            320 non-null    object 
 5   GPU                  320 non-null    object 
 6   Screen               320 non-null    object 
 7   Warranty             320 non-null    object 
 8   Stock                320 non-null    object 
 9   Status               320 non-null    object 
dtypes: float64(1), object(9)
memory usage: 25.1+ KB


#### Problem 2: Column name 'RAM'
* Type: Object

In [88]:
df['RAM'].dtype

dtype('O')

In [89]:
df['RAM']
# list_price1 = []
# for i in range(len(df['RAM'])):
#   price_ = str(df['Price'][i])
#   price_ =
#   price_ = int(price_.replace('.',''))/1000000
#   list_price1.append(price_)
# # list_price1
# df['Price'] = list_price1
# df = df.rename(columns={'Price': 'Price (Million VND)'})
# df

0      16GB
1      16GB
2       8GB
3      16GB
4      16GB
       ... 
315     8GB
316     8GB
317     8GB
318    16GB
319     8GB
Name: RAM, Length: 320, dtype: object